### ISSUE TITLE
Separate code generation in diferent files when using include in XSD

### ISSUE THREAD

**Issue by flonou** [kmpm/xsd2code#13]
For now, when transforming an XSD to code, there is only one output file for all the elements, even if the XSD includes another one.
This prevents including an XSD in multiple other ones in the same namespace as the code of the included XSDs will be duplicated

**Comment by kmpm** [comment]
Example files please, and since it's close to Christmas I wish to get a pull-request.

**Comment by flonou** [comment]
Hmm I can't add this file type to the comment.
I'm writing a test case to show the "issue"

If we want to generate both AnimatedShow and TVShow and include them in the same project/namespace, we will have an error because ksgender and others types will be defined twice, once in each generated file. So my proposition is to generate separate C# files for the included and imported schemas. The problem is how to decide their name and detect they already exist

A workaround is to create an xsd including both AnimatedShow and TVShow to generate only one file

**Comment by flonou** [comment]
fixed in #15
