### ISSUE TITLE
Missing integration with VS 2015

### ISSUE THREAD

**Issue by kmpm** [kmpm/xsd2code#2]
Create as VSIX

**Comment by flonou** [comment]
I just made some tests and successfully created a VSIX extension with the same functionnality as the original addin project
I would suggest to create a new project containing the configuration form and remove the addin project

**Comment by kmpm** [comment]
You are officially my hero...

Just dump my placeholder and replace it with whatever you made in a pull-request.

**Comment by kmpm** [comment]
Closed by pr #7
